font_size 10
font_family Cascadia Mono
disable_ligatures always

window_padding_width 4
hide_window_decorations yes

scrollback_lines 65536
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

include current-theme.conf
