# Keep this setting intact when reporting bugs
LC_MESSAGES=C.utf8

COMMON_FLAGS="-march=x86-64-v3 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

FEATURES="buildpkg"
BINPKG_FORMAT="gpkg"

MAKEOPTS="-j14"
EMERGE_DEFAULT_OPTS="--ask --ask-enter-invalid --autounmask=n"

ACCEPT_LICENSE="*"
INPUT_DEVICES="libinput"
VIDEO_CARDS="amdgpu radeonsi radeon intel"
USE="dist-kernel man screencast vaapi vpx -gnome-online-accounts"
